package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaApartamentoGaragem generated by hbm2java
 */
@Entity
@Table(name="ta_apartamento_garagem"
    ,catalog="db_gecon"
)
public class TaApartamentoGaragem  implements java.io.Serializable {


     private Integer idtApartamentoGaragem;
     private TbApartamento tbApartamento;
     private TbGaragem tbGaragem;

    public TaApartamentoGaragem() {
    }

    public TaApartamentoGaragem(TbApartamento tbApartamento, TbGaragem tbGaragem) {
       this.tbApartamento = tbApartamento;
       this.tbGaragem = tbGaragem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_apartamento_garagem", unique=true, nullable=false)
    public Integer getIdtApartamentoGaragem() {
        return this.idtApartamentoGaragem;
    }
    
    public void setIdtApartamentoGaragem(Integer idtApartamentoGaragem) {
        this.idtApartamentoGaragem = idtApartamentoGaragem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_cod_apartamento", nullable=false)
    public TbApartamento getTbApartamento() {
        return this.tbApartamento;
    }
    
    public void setTbApartamento(TbApartamento tbApartamento) {
        this.tbApartamento = tbApartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_cod_garagem", nullable=false)
    public TbGaragem getTbGaragem() {
        return this.tbGaragem;
    }
    
    public void setTbGaragem(TbGaragem tbGaragem) {
        this.tbGaragem = tbGaragem;
    }




}


