package pojo;
// Generated 19/04/2018 19:35:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaApartamentoPessoa generated by hbm2java
 */
@Entity
@Table(name="ta_apartamento_pessoa"
    ,catalog="db_gecon"
)
public class TaApartamentoPessoa  implements java.io.Serializable {


     private Integer idtApartamentoPessoa;
     private TbApartamento tbApartamento;
     private TbPessoa tbPessoa;
     private Date dtaEntrada;
     private Date dtaSaida;

    public TaApartamentoPessoa() {
    }

	
    public TaApartamentoPessoa(TbApartamento tbApartamento, TbPessoa tbPessoa, Date dtaEntrada) {
        this.tbApartamento = tbApartamento;
        this.tbPessoa = tbPessoa;
        this.dtaEntrada = dtaEntrada;
    }
    public TaApartamentoPessoa(TbApartamento tbApartamento, TbPessoa tbPessoa, Date dtaEntrada, Date dtaSaida) {
       this.tbApartamento = tbApartamento;
       this.tbPessoa = tbPessoa;
       this.dtaEntrada = dtaEntrada;
       this.dtaSaida = dtaSaida;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_apartamento_pessoa", unique=true, nullable=false)
    public Integer getIdtApartamentoPessoa() {
        return this.idtApartamentoPessoa;
    }
    
    public void setIdtApartamentoPessoa(Integer idtApartamentoPessoa) {
        this.idtApartamentoPessoa = idtApartamentoPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_apartamento", nullable=false)
    public TbApartamento getTbApartamento() {
        return this.tbApartamento;
    }
    
    public void setTbApartamento(TbApartamento tbApartamento) {
        this.tbApartamento = tbApartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_entrada", nullable=false, length=10)
    public Date getDtaEntrada() {
        return this.dtaEntrada;
    }
    
    public void setDtaEntrada(Date dtaEntrada) {
        this.dtaEntrada = dtaEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_saida", length=10)
    public Date getDtaSaida() {
        return this.dtaSaida;
    }
    
    public void setDtaSaida(Date dtaSaida) {
        this.dtaSaida = dtaSaida;
    }




}


