package pojo;
// Generated 06/05/2018 18:32:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaVisita generated by hbm2java
 */
@Entity
@Table(name="ta_visita"
    ,catalog="db_gecon"
)
public class TaVisita  implements java.io.Serializable, Comparable<TaVisita>  {


     private Integer idtVisita;
     private TaMorador taMorador;
     private TbPessoa tbPessoa;
     private Date dtaInicioVisita;
     private Date dtaFinalVisita;

    public TaVisita() {
    }

	
    public TaVisita(TaMorador taMorador, TbPessoa tbPessoa, Date dtaInicioVisita) {
        this.taMorador = taMorador;
        this.tbPessoa = tbPessoa;
        this.dtaInicioVisita = dtaInicioVisita;
    }
    public TaVisita(TaMorador taMorador, TbPessoa tbPessoa, Date dtaInicioVisita, Date dtaFinalVisita) {
       this.taMorador = taMorador;
       this.tbPessoa = tbPessoa;
       this.dtaInicioVisita = dtaInicioVisita;
       this.dtaFinalVisita = dtaFinalVisita;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_visita", unique=true, nullable=false)
    public Integer getIdtVisita() {
        return this.idtVisita;
    }
    
    public void setIdtVisita(Integer idtVisita) {
        this.idtVisita = idtVisita;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_morador", nullable=false)
    public TaMorador getTaMorador() {
        return this.taMorador;
    }
    
    public void setTaMorador(TaMorador taMorador) {
        this.taMorador = taMorador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_inicio_visita", nullable=false, length=10)
    public Date getDtaInicioVisita() {
        return this.dtaInicioVisita;
    }
    
    public void setDtaInicioVisita(Date dtaInicioVisita) {
        this.dtaInicioVisita = dtaInicioVisita;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_final_visita", length=10)
    public Date getDtaFinalVisita() {
        return this.dtaFinalVisita;
    }
    
    public void setDtaFinalVisita(Date dtaFinalVisita) {
        this.dtaFinalVisita = dtaFinalVisita;
    }

    @Override
    public int compareTo(TaVisita visita) {
        if(this.dtaInicioVisita.getTime() < visita.dtaInicioVisita.getTime()){
            return -1;
        }else if(this.dtaInicioVisita.getTime() > visita.dtaInicioVisita.getTime()){
            return 1;
        }
        return 0;
        
    }


}


