package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbApartamento generated by hbm2java
 */
@Entity
@Table(name="tb_apartamento"
    ,catalog="db_gecon"
)
public class TbApartamento  implements java.io.Serializable {


     private Integer idtApartamento;
     private TbCondominio tbCondominio;
     private String blocoApartamento;
     private String numApartamento;
     private Date dtaEntradaApartamento;
     private Date dtaSaidaApartamento;
     private Set<TaApartamentoGaragem> taApartamentoGaragems = new HashSet<TaApartamentoGaragem>(0);
     private Set<TbForum> tbForums = new HashSet<TbForum>(0);
     private Set<TbPessoa> tbPessoas = new HashSet<TbPessoa>(0);

    public TbApartamento() {
    }

	
    public TbApartamento(TbCondominio tbCondominio, String numApartamento, Date dtaEntradaApartamento) {
        this.tbCondominio = tbCondominio;
        this.numApartamento = numApartamento;
        this.dtaEntradaApartamento = dtaEntradaApartamento;
    }
    public TbApartamento(TbCondominio tbCondominio, String blocoApartamento, String numApartamento, Date dtaEntradaApartamento, Date dtaSaidaApartamento, Set<TaApartamentoGaragem> taApartamentoGaragems, Set<TbForum> tbForums, Set<TbPessoa> tbPessoas) {
       this.tbCondominio = tbCondominio;
       this.blocoApartamento = blocoApartamento;
       this.numApartamento = numApartamento;
       this.dtaEntradaApartamento = dtaEntradaApartamento;
       this.dtaSaidaApartamento = dtaSaidaApartamento;
       this.taApartamentoGaragems = taApartamentoGaragems;
       this.tbForums = tbForums;
       this.tbPessoas = tbPessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_apartamento", unique=true, nullable=false)
    public Integer getIdtApartamento() {
        return this.idtApartamento;
    }
    
    public void setIdtApartamento(Integer idtApartamento) {
        this.idtApartamento = idtApartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_condominio", nullable=false)
    public TbCondominio getTbCondominio() {
        return this.tbCondominio;
    }
    
    public void setTbCondominio(TbCondominio tbCondominio) {
        this.tbCondominio = tbCondominio;
    }

    
    @Column(name="bloco_apartamento", length=45)
    public String getBlocoApartamento() {
        return this.blocoApartamento;
    }
    
    public void setBlocoApartamento(String blocoApartamento) {
        this.blocoApartamento = blocoApartamento;
    }

    
    @Column(name="num_apartamento", nullable=false, length=45)
    public String getNumApartamento() {
        return this.numApartamento;
    }
    
    public void setNumApartamento(String numApartamento) {
        this.numApartamento = numApartamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_entrada_apartamento", nullable=false, length=10)
    public Date getDtaEntradaApartamento() {
        return this.dtaEntradaApartamento;
    }
    
    public void setDtaEntradaApartamento(Date dtaEntradaApartamento) {
        this.dtaEntradaApartamento = dtaEntradaApartamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_saida_apartamento", length=10)
    public Date getDtaSaidaApartamento() {
        return this.dtaSaidaApartamento;
    }
    
    public void setDtaSaidaApartamento(Date dtaSaidaApartamento) {
        this.dtaSaidaApartamento = dtaSaidaApartamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbApartamento")
    public Set<TaApartamentoGaragem> getTaApartamentoGaragems() {
        return this.taApartamentoGaragems;
    }
    
    public void setTaApartamentoGaragems(Set<TaApartamentoGaragem> taApartamentoGaragems) {
        this.taApartamentoGaragems = taApartamentoGaragems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbApartamento")
    public Set<TbForum> getTbForums() {
        return this.tbForums;
    }
    
    public void setTbForums(Set<TbForum> tbForums) {
        this.tbForums = tbForums;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbApartamento")
    public Set<TbPessoa> getTbPessoas() {
        return this.tbPessoas;
    }
    
    public void setTbPessoas(Set<TbPessoa> tbPessoas) {
        this.tbPessoas = tbPessoas;
    }




}


