package pojo;
// Generated 19/04/2018 19:35:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCidade generated by hbm2java
 */
@Entity
@Table(name="tb_cidade"
    ,catalog="db_gecon"
)
public class TbCidade  implements java.io.Serializable {


     private Integer idtCidade;
     private String nmeCidade;
     private String sglEstadoCidade;
     private Set<TbCondominio> tbCondominios = new HashSet<TbCondominio>(0);

    public TbCidade() {
    }

	
    public TbCidade(String nmeCidade, String sglEstadoCidade) {
        this.nmeCidade = nmeCidade;
        this.sglEstadoCidade = sglEstadoCidade;
    }
    public TbCidade(String nmeCidade, String sglEstadoCidade, Set<TbCondominio> tbCondominios) {
       this.nmeCidade = nmeCidade;
       this.sglEstadoCidade = sglEstadoCidade;
       this.tbCondominios = tbCondominios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_cidade", unique=true, nullable=false)
    public Integer getIdtCidade() {
        return this.idtCidade;
    }
    
    public void setIdtCidade(Integer idtCidade) {
        this.idtCidade = idtCidade;
    }

    
    @Column(name="nme_cidade", nullable=false, length=50)
    public String getNmeCidade() {
        return this.nmeCidade;
    }
    
    public void setNmeCidade(String nmeCidade) {
        this.nmeCidade = nmeCidade;
    }

    
    @Column(name="sgl_estado_cidade", nullable=false, length=2)
    public String getSglEstadoCidade() {
        return this.sglEstadoCidade;
    }
    
    public void setSglEstadoCidade(String sglEstadoCidade) {
        this.sglEstadoCidade = sglEstadoCidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCidade")
    public Set<TbCondominio> getTbCondominios() {
        return this.tbCondominios;
    }
    
    public void setTbCondominios(Set<TbCondominio> tbCondominios) {
        this.tbCondominios = tbCondominios;
    }




}


