package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCidade generated by hbm2java
 */
@Entity
@Table(name="tb_cidade"
    ,catalog="db_gecon"
)
public class TbCidade  implements java.io.Serializable {


     private Integer idtCidade;
     private TbEstado tbEstado;
     private String nmeCidade;
     private Set<TbCondominio> tbCondominios = new HashSet<TbCondominio>(0);

    public TbCidade() {
    }

	
    public TbCidade(TbEstado tbEstado) {
        this.tbEstado = tbEstado;
    }
    public TbCidade(TbEstado tbEstado, String nmeCidade, Set<TbCondominio> tbCondominios) {
       this.tbEstado = tbEstado;
       this.nmeCidade = nmeCidade;
       this.tbCondominios = tbCondominios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_cidade", unique=true, nullable=false)
    public Integer getIdtCidade() {
        return this.idtCidade;
    }
    
    public void setIdtCidade(Integer idtCidade) {
        this.idtCidade = idtCidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estado", nullable=false)
    public TbEstado getTbEstado() {
        return this.tbEstado;
    }
    
    public void setTbEstado(TbEstado tbEstado) {
        this.tbEstado = tbEstado;
    }

    
    @Column(name="nme_cidade", length=50)
    public String getNmeCidade() {
        return this.nmeCidade;
    }
    
    public void setNmeCidade(String nmeCidade) {
        this.nmeCidade = nmeCidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCidade")
    public Set<TbCondominio> getTbCondominios() {
        return this.tbCondominios;
    }
    
    public void setTbCondominios(Set<TbCondominio> tbCondominios) {
        this.tbCondominios = tbCondominios;
    }




}


