package pojo;
// Generated 06/05/2018 18:32:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCondominio generated by hbm2java
 */
@Entity
@Table(name="tb_condominio"
    ,catalog="db_gecon"
)
public class TbCondominio  implements java.io.Serializable {


     private Integer idtCondominio;
     private String nmeCondominio;
     private String dscLocalCondominio;
     private Set<TbAreaLazer> tbAreaLazers = new HashSet<TbAreaLazer>(0);
     private Set<TbResidencia> tbResidencias = new HashSet<TbResidencia>(0);

    public TbCondominio() {
    }

	
    public TbCondominio(String nmeCondominio, String dscLocalCondominio) {
        this.nmeCondominio = nmeCondominio;
        this.dscLocalCondominio = dscLocalCondominio;
    }
    public TbCondominio(String nmeCondominio, String dscLocalCondominio, Set<TbAreaLazer> tbAreaLazers, Set<TbResidencia> tbResidencias) {
       this.nmeCondominio = nmeCondominio;
       this.dscLocalCondominio = dscLocalCondominio;
       this.tbAreaLazers = tbAreaLazers;
       this.tbResidencias = tbResidencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_condominio", unique=true, nullable=false)
    public Integer getIdtCondominio() {
        return this.idtCondominio;
    }
    
    public void setIdtCondominio(Integer idtCondominio) {
        this.idtCondominio = idtCondominio;
    }

    
    @Column(name="nme_condominio", nullable=false, length=45)
    public String getNmeCondominio() {
        return this.nmeCondominio;
    }
    
    public void setNmeCondominio(String nmeCondominio) {
        this.nmeCondominio = nmeCondominio;
    }

    
    @Column(name="dsc_local_condominio", nullable=false, length=65535)
    public String getDscLocalCondominio() {
        return this.dscLocalCondominio;
    }
    
    public void setDscLocalCondominio(String dscLocalCondominio) {
        this.dscLocalCondominio = dscLocalCondominio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCondominio")
    public Set<TbAreaLazer> getTbAreaLazers() {
        return this.tbAreaLazers;
    }
    
    public void setTbAreaLazers(Set<TbAreaLazer> tbAreaLazers) {
        this.tbAreaLazers = tbAreaLazers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCondominio")
    public Set<TbResidencia> getTbResidencias() {
        return this.tbResidencias;
    }
    
    public void setTbResidencias(Set<TbResidencia> tbResidencias) {
        this.tbResidencias = tbResidencias;
    }




}


