package pojo;
// Generated 19/04/2018 19:35:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCondominio generated by hbm2java
 */
@Entity
@Table(name="tb_condominio"
    ,catalog="db_gecon"
)
public class TbCondominio  implements java.io.Serializable {


     private Integer idtCondominio;
     private TbCidade tbCidade;
     private String nmeCondominio;
     private String imgCondominio;
     private Set<TbApartamento> tbApartamentos = new HashSet<TbApartamento>(0);

    public TbCondominio() {
    }

	
    public TbCondominio(TbCidade tbCidade, String nmeCondominio) {
        this.tbCidade = tbCidade;
        this.nmeCondominio = nmeCondominio;
    }
    public TbCondominio(TbCidade tbCidade, String nmeCondominio, String imgCondominio, Set<TbApartamento> tbApartamentos) {
       this.tbCidade = tbCidade;
       this.nmeCondominio = nmeCondominio;
       this.imgCondominio = imgCondominio;
       this.tbApartamentos = tbApartamentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_condominio", unique=true, nullable=false)
    public Integer getIdtCondominio() {
        return this.idtCondominio;
    }
    
    public void setIdtCondominio(Integer idtCondominio) {
        this.idtCondominio = idtCondominio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_cidade", nullable=false)
    public TbCidade getTbCidade() {
        return this.tbCidade;
    }
    
    public void setTbCidade(TbCidade tbCidade) {
        this.tbCidade = tbCidade;
    }

    
    @Column(name="nme_condominio", nullable=false, length=45)
    public String getNmeCondominio() {
        return this.nmeCondominio;
    }
    
    public void setNmeCondominio(String nmeCondominio) {
        this.nmeCondominio = nmeCondominio;
    }

    
    @Column(name="img_condominio", length=100)
    public String getImgCondominio() {
        return this.imgCondominio;
    }
    
    public void setImgCondominio(String imgCondominio) {
        this.imgCondominio = imgCondominio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCondominio")
    public Set<TbApartamento> getTbApartamentos() {
        return this.tbApartamentos;
    }
    
    public void setTbApartamentos(Set<TbApartamento> tbApartamentos) {
        this.tbApartamentos = tbApartamentos;
    }




}


