package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEstado generated by hbm2java
 */
@Entity
@Table(name="tb_estado"
    ,catalog="db_gecon"
)
public class TbEstado  implements java.io.Serializable {


     private String idtEstado;
     private Set<TbCidade> tbCidades = new HashSet<TbCidade>(0);

    public TbEstado() {
    }

	
    public TbEstado(String idtEstado) {
        this.idtEstado = idtEstado;
    }
    public TbEstado(String idtEstado, Set<TbCidade> tbCidades) {
       this.idtEstado = idtEstado;
       this.tbCidades = tbCidades;
    }
   
     @Id 

    
    @Column(name="idt_estado", unique=true, nullable=false, length=2)
    public String getIdtEstado() {
        return this.idtEstado;
    }
    
    public void setIdtEstado(String idtEstado) {
        this.idtEstado = idtEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbEstado")
    public Set<TbCidade> getTbCidades() {
        return this.tbCidades;
    }
    
    public void setTbCidades(Set<TbCidade> tbCidades) {
        this.tbCidades = tbCidades;
    }




}


