package pojo;
// Generated 26/04/2018 19:07:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbForum generated by hbm2java
 */
@Entity
@Table(name="tb_forum"
    ,catalog="db_gecon"
)
public class TbForum  implements java.io.Serializable {


     private Integer idtForum;
     private TaMorador taMorador;
     private String titForum;
     private String dscForum;
     private Date dtaCadastroForum;
     private Set<TbMensagem> tbMensagems = new HashSet<TbMensagem>(0);

    public TbForum() {
    }

	
    public TbForum(TaMorador taMorador, String titForum, String dscForum, Date dtaCadastroForum) {
        this.taMorador = taMorador;
        this.titForum = titForum;
        this.dscForum = dscForum;
        this.dtaCadastroForum = dtaCadastroForum;
    }
    public TbForum(TaMorador taMorador, String titForum, String dscForum, Date dtaCadastroForum, Set<TbMensagem> tbMensagems) {
       this.taMorador = taMorador;
       this.titForum = titForum;
       this.dscForum = dscForum;
       this.dtaCadastroForum = dtaCadastroForum;
       this.tbMensagems = tbMensagems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_forum", unique=true, nullable=false)
    public Integer getIdtForum() {
        return this.idtForum;
    }
    
    public void setIdtForum(Integer idtForum) {
        this.idtForum = idtForum;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_morador", nullable=false)
    public TaMorador getTaMorador() {
        return this.taMorador;
    }
    
    public void setTaMorador(TaMorador taMorador) {
        this.taMorador = taMorador;
    }

    
    @Column(name="tit_forum", nullable=false)
    public String getTitForum() {
        return this.titForum;
    }
    
    public void setTitForum(String titForum) {
        this.titForum = titForum;
    }

    
    @Column(name="dsc_forum", nullable=false, length=65535)
    public String getDscForum() {
        return this.dscForum;
    }
    
    public void setDscForum(String dscForum) {
        this.dscForum = dscForum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_cadastro_forum", nullable=false, length=19)
    public Date getDtaCadastroForum() {
        return this.dtaCadastroForum;
    }
    
    public void setDtaCadastroForum(Date dtaCadastroForum) {
        this.dtaCadastroForum = dtaCadastroForum;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbForum")
    public Set<TbMensagem> getTbMensagems() {
        return this.tbMensagems;
    }
    
    public void setTbMensagems(Set<TbMensagem> tbMensagems) {
        this.tbMensagems = tbMensagems;
    }




}


