package pojo;
// Generated 05/05/2018 15:34:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbGaragem generated by hbm2java
 */
@Entity
@Table(name="tb_garagem"
    ,catalog="db_gecon"
)
public class TbGaragem  implements java.io.Serializable {


     private Integer idtGaragem;
     private TbResidencia tbResidencia;
     private String dscGaragem;

    public TbGaragem() {
    }

    public TbGaragem(TbResidencia tbResidencia, String dscGaragem) {
       this.tbResidencia = tbResidencia;
       this.dscGaragem = dscGaragem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_garagem", unique=true, nullable=false)
    public Integer getIdtGaragem() {
        return this.idtGaragem;
    }
    
    public void setIdtGaragem(Integer idtGaragem) {
        this.idtGaragem = idtGaragem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_residencia", nullable=false)
    public TbResidencia getTbResidencia() {
        return this.tbResidencia;
    }
    
    public void setTbResidencia(TbResidencia tbResidencia) {
        this.tbResidencia = tbResidencia;
    }

    
    @Column(name="dsc_garagem", nullable=false)
    public String getDscGaragem() {
        return this.dscGaragem;
    }
    
    public void setDscGaragem(String dscGaragem) {
        this.dscGaragem = dscGaragem;
    }




}


