package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbGaragem generated by hbm2java
 */
@Entity
@Table(name="tb_garagem"
    ,catalog="db_gecon"
)
public class TbGaragem  implements java.io.Serializable {


     private Integer idtGaragem;
     private int numGaragem;
     private Set<TaApartamentoGaragem> taApartamentoGaragems = new HashSet<TaApartamentoGaragem>(0);

    public TbGaragem() {
    }

	
    public TbGaragem(int numGaragem) {
        this.numGaragem = numGaragem;
    }
    public TbGaragem(int numGaragem, Set<TaApartamentoGaragem> taApartamentoGaragems) {
       this.numGaragem = numGaragem;
       this.taApartamentoGaragems = taApartamentoGaragems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_garagem", unique=true, nullable=false)
    public Integer getIdtGaragem() {
        return this.idtGaragem;
    }
    
    public void setIdtGaragem(Integer idtGaragem) {
        this.idtGaragem = idtGaragem;
    }

    
    @Column(name="num_garagem", nullable=false)
    public int getNumGaragem() {
        return this.numGaragem;
    }
    
    public void setNumGaragem(int numGaragem) {
        this.numGaragem = numGaragem;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbGaragem")
    public Set<TaApartamentoGaragem> getTaApartamentoGaragems() {
        return this.taApartamentoGaragems;
    }
    
    public void setTaApartamentoGaragems(Set<TaApartamentoGaragem> taApartamentoGaragems) {
        this.taApartamentoGaragems = taApartamentoGaragems;
    }




}


