package pojo;
// Generated 26/04/2018 19:07:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMensagem generated by hbm2java
 */
@Entity
@Table(name="tb_mensagem"
    ,catalog="db_gecon"
)
public class TbMensagem  implements java.io.Serializable {


     private int idtMensagem;
     private TaMorador taMorador;
     private TbForum tbForum;
     private String txtMensagem;
     private Date dtaMensagem;

    public TbMensagem() {
    }

    public TbMensagem(int idtMensagem, TaMorador taMorador, TbForum tbForum, String txtMensagem, Date dtaMensagem) {
       this.idtMensagem = idtMensagem;
       this.taMorador = taMorador;
       this.tbForum = tbForum;
       this.txtMensagem = txtMensagem;
       this.dtaMensagem = dtaMensagem;
    }
   
     @Id 

    
    @Column(name="idt_mensagem", unique=true, nullable=false)
    public int getIdtMensagem() {
        return this.idtMensagem;
    }
    
    public void setIdtMensagem(int idtMensagem) {
        this.idtMensagem = idtMensagem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_morador", nullable=false)
    public TaMorador getTaMorador() {
        return this.taMorador;
    }
    
    public void setTaMorador(TaMorador taMorador) {
        this.taMorador = taMorador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_forum", nullable=false)
    public TbForum getTbForum() {
        return this.tbForum;
    }
    
    public void setTbForum(TbForum tbForum) {
        this.tbForum = tbForum;
    }

    
    @Column(name="txt_mensagem", nullable=false, length=65535)
    public String getTxtMensagem() {
        return this.txtMensagem;
    }
    
    public void setTxtMensagem(String txtMensagem) {
        this.txtMensagem = txtMensagem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_mensagem", nullable=false, length=19)
    public Date getDtaMensagem() {
        return this.dtaMensagem;
    }
    
    public void setDtaMensagem(Date dtaMensagem) {
        this.dtaMensagem = dtaMensagem;
    }




}


