package pojo;
// Generated 19/04/2018 19:35:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMensagem generated by hbm2java
 */
@Entity
@Table(name="tb_mensagem"
    ,catalog="db_gecon"
)
public class TbMensagem  implements java.io.Serializable {


     private Integer idtbMensagem;
     private TbForum tbForum;
     private TbPessoa tbPessoa;
     private String msgMensagem;
     private Date dtaMensagem;

    public TbMensagem() {
    }

	
    public TbMensagem(TbForum tbForum, TbPessoa tbPessoa, Date dtaMensagem) {
        this.tbForum = tbForum;
        this.tbPessoa = tbPessoa;
        this.dtaMensagem = dtaMensagem;
    }
    public TbMensagem(TbForum tbForum, TbPessoa tbPessoa, String msgMensagem, Date dtaMensagem) {
       this.tbForum = tbForum;
       this.tbPessoa = tbPessoa;
       this.msgMensagem = msgMensagem;
       this.dtaMensagem = dtaMensagem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtb_mensagem", unique=true, nullable=false)
    public Integer getIdtbMensagem() {
        return this.idtbMensagem;
    }
    
    public void setIdtbMensagem(Integer idtbMensagem) {
        this.idtbMensagem = idtbMensagem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_forum", nullable=false)
    public TbForum getTbForum() {
        return this.tbForum;
    }
    
    public void setTbForum(TbForum tbForum) {
        this.tbForum = tbForum;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

    
    @Column(name="msg_mensagem", length=800)
    public String getMsgMensagem() {
        return this.msgMensagem;
    }
    
    public void setMsgMensagem(String msgMensagem) {
        this.msgMensagem = msgMensagem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_mensagem", nullable=false, length=19)
    public Date getDtaMensagem() {
        return this.dtaMensagem;
    }
    
    public void setDtaMensagem(Date dtaMensagem) {
        this.dtaMensagem = dtaMensagem;
    }




}


