package pojo;
// Generated 19/04/2018 19:35:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbOcorrencia generated by hbm2java
 */
@Entity
@Table(name="tb_ocorrencia"
    ,catalog="db_gecon"
)
public class TbOcorrencia  implements java.io.Serializable {


     private Integer idtOcorrencia;
     private TbPessoa tbPessoa;
     private Date dtaOcorrencia;
     private String txtOcorrencia;

    public TbOcorrencia() {
    }

    public TbOcorrencia(TbPessoa tbPessoa, Date dtaOcorrencia, String txtOcorrencia) {
       this.tbPessoa = tbPessoa;
       this.dtaOcorrencia = dtaOcorrencia;
       this.txtOcorrencia = txtOcorrencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_ocorrencia", unique=true, nullable=false)
    public Integer getIdtOcorrencia() {
        return this.idtOcorrencia;
    }
    
    public void setIdtOcorrencia(Integer idtOcorrencia) {
        this.idtOcorrencia = idtOcorrencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_ocorrencia", nullable=false, length=10)
    public Date getDtaOcorrencia() {
        return this.dtaOcorrencia;
    }
    
    public void setDtaOcorrencia(Date dtaOcorrencia) {
        this.dtaOcorrencia = dtaOcorrencia;
    }

    
    @Column(name="txt_ocorrencia", nullable=false, length=65535)
    public String getTxtOcorrencia() {
        return this.txtOcorrencia;
    }
    
    public void setTxtOcorrencia(String txtOcorrencia) {
        this.txtOcorrencia = txtOcorrencia;
    }




}


