package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbPessoa generated by hbm2java
 */
@Entity
@Table(name="tb_pessoa"
    ,catalog="db_gecon"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf_pessoa") 
)
public class TbPessoa  implements java.io.Serializable {


     private Integer idtPessoa;
     private TbApartamento tbApartamento;
     private TdPerfil tdPerfil;
     private String nmePessoa;
     private int cpfPessoa;
     private Date dtaNascimentoPessoa;
     private Character generoPessoa;
     private String fotoPessoa;
     private Set<TbReserva> tbReservas = new HashSet<TbReserva>(0);
     private Set<TbOcorrencia> tbOcorrencias = new HashSet<TbOcorrencia>(0);
     private Set<TbMensagem> tbMensagems = new HashSet<TbMensagem>(0);

    public TbPessoa() {
    }

	
    public TbPessoa(TdPerfil tdPerfil, String nmePessoa, int cpfPessoa) {
        this.tdPerfil = tdPerfil;
        this.nmePessoa = nmePessoa;
        this.cpfPessoa = cpfPessoa;
    }
    public TbPessoa(TbApartamento tbApartamento, TdPerfil tdPerfil, String nmePessoa, int cpfPessoa, Date dtaNascimentoPessoa, Character generoPessoa, String fotoPessoa, Set<TbReserva> tbReservas, Set<TbOcorrencia> tbOcorrencias, Set<TbMensagem> tbMensagems) {
       this.tbApartamento = tbApartamento;
       this.tdPerfil = tdPerfil;
       this.nmePessoa = nmePessoa;
       this.cpfPessoa = cpfPessoa;
       this.dtaNascimentoPessoa = dtaNascimentoPessoa;
       this.generoPessoa = generoPessoa;
       this.fotoPessoa = fotoPessoa;
       this.tbReservas = tbReservas;
       this.tbOcorrencias = tbOcorrencias;
       this.tbMensagems = tbMensagems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_pessoa", unique=true, nullable=false)
    public Integer getIdtPessoa() {
        return this.idtPessoa;
    }
    
    public void setIdtPessoa(Integer idtPessoa) {
        this.idtPessoa = idtPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_cod_apartamento")
    public TbApartamento getTbApartamento() {
        return this.tbApartamento;
    }
    
    public void setTbApartamento(TbApartamento tbApartamento) {
        this.tbApartamento = tbApartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="td_cod_perfil", nullable=false)
    public TdPerfil getTdPerfil() {
        return this.tdPerfil;
    }
    
    public void setTdPerfil(TdPerfil tdPerfil) {
        this.tdPerfil = tdPerfil;
    }

    
    @Column(name="nme_pessoa", nullable=false, length=100)
    public String getNmePessoa() {
        return this.nmePessoa;
    }
    
    public void setNmePessoa(String nmePessoa) {
        this.nmePessoa = nmePessoa;
    }

    
    @Column(name="cpf_pessoa", unique=true, nullable=false)
    public int getCpfPessoa() {
        return this.cpfPessoa;
    }
    
    public void setCpfPessoa(int cpfPessoa) {
        this.cpfPessoa = cpfPessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_nascimento_pessoa", length=10)
    public Date getDtaNascimentoPessoa() {
        return this.dtaNascimentoPessoa;
    }
    
    public void setDtaNascimentoPessoa(Date dtaNascimentoPessoa) {
        this.dtaNascimentoPessoa = dtaNascimentoPessoa;
    }

    
    @Column(name="genero_pessoa", length=1)
    public Character getGeneroPessoa() {
        return this.generoPessoa;
    }
    
    public void setGeneroPessoa(Character generoPessoa) {
        this.generoPessoa = generoPessoa;
    }

    
    @Column(name="foto_pessoa", length=100)
    public String getFotoPessoa() {
        return this.fotoPessoa;
    }
    
    public void setFotoPessoa(String fotoPessoa) {
        this.fotoPessoa = fotoPessoa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbReserva> getTbReservas() {
        return this.tbReservas;
    }
    
    public void setTbReservas(Set<TbReserva> tbReservas) {
        this.tbReservas = tbReservas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbOcorrencia> getTbOcorrencias() {
        return this.tbOcorrencias;
    }
    
    public void setTbOcorrencias(Set<TbOcorrencia> tbOcorrencias) {
        this.tbOcorrencias = tbOcorrencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPessoa")
    public Set<TbMensagem> getTbMensagems() {
        return this.tbMensagems;
    }
    
    public void setTbMensagems(Set<TbMensagem> tbMensagems) {
        this.tbMensagems = tbMensagems;
    }




}


