package pojo;
// Generated 26/04/2018 19:07:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbReserva generated by hbm2java
 */
@Entity
@Table(name="tb_reserva"
    ,catalog="db_gecon"
)
public class TbReserva  implements java.io.Serializable {


     private int idtReserva;
     private TbAreaLazer tbAreaLazer;
     private TbResidencia tbResidencia;
     private Date dtaInicioReserva;
     private Date dtaFimReserva;
     private Date dtaCadastroReserva;
     private char stsConfirmadoReserva;

    public TbReserva() {
    }

    public TbReserva(int idtReserva, TbAreaLazer tbAreaLazer, TbResidencia tbResidencia, Date dtaInicioReserva, Date dtaFimReserva, Date dtaCadastroReserva, char stsConfirmadoReserva) {
       this.idtReserva = idtReserva;
       this.tbAreaLazer = tbAreaLazer;
       this.tbResidencia = tbResidencia;
       this.dtaInicioReserva = dtaInicioReserva;
       this.dtaFimReserva = dtaFimReserva;
       this.dtaCadastroReserva = dtaCadastroReserva;
       this.stsConfirmadoReserva = stsConfirmadoReserva;
    }
   
     @Id 

    
    @Column(name="idt_reserva", unique=true, nullable=false)
    public int getIdtReserva() {
        return this.idtReserva;
    }
    
    public void setIdtReserva(int idtReserva) {
        this.idtReserva = idtReserva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_area_lazer", nullable=false)
    public TbAreaLazer getTbAreaLazer() {
        return this.tbAreaLazer;
    }
    
    public void setTbAreaLazer(TbAreaLazer tbAreaLazer) {
        this.tbAreaLazer = tbAreaLazer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_residencia", nullable=false)
    public TbResidencia getTbResidencia() {
        return this.tbResidencia;
    }
    
    public void setTbResidencia(TbResidencia tbResidencia) {
        this.tbResidencia = tbResidencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_inicio_reserva", nullable=false, length=19)
    public Date getDtaInicioReserva() {
        return this.dtaInicioReserva;
    }
    
    public void setDtaInicioReserva(Date dtaInicioReserva) {
        this.dtaInicioReserva = dtaInicioReserva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_fim_reserva", nullable=false, length=19)
    public Date getDtaFimReserva() {
        return this.dtaFimReserva;
    }
    
    public void setDtaFimReserva(Date dtaFimReserva) {
        this.dtaFimReserva = dtaFimReserva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_cadastro_reserva", nullable=false, length=19)
    public Date getDtaCadastroReserva() {
        return this.dtaCadastroReserva;
    }
    
    public void setDtaCadastroReserva(Date dtaCadastroReserva) {
        this.dtaCadastroReserva = dtaCadastroReserva;
    }

    
    @Column(name="sts_confirmado_reserva", nullable=false, length=1)
    public char getStsConfirmadoReserva() {
        return this.stsConfirmadoReserva;
    }
    
    public void setStsConfirmadoReserva(char stsConfirmadoReserva) {
        this.stsConfirmadoReserva = stsConfirmadoReserva;
    }




}


