package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbReserva generated by hbm2java
 */
@Entity
@Table(name="tb_reserva"
    ,catalog="db_gecon"
)
public class TbReserva  implements java.io.Serializable {


     private Integer idtReserva;
     private TbLazer tbLazer;
     private TbPessoa tbPessoa;
     private Date dtaReserva;
     private Date dtiInicioReserva;
     private Date dtiFimReserva;
     private boolean flagConfirma;
     private Date dtaCadastroReserva;

    public TbReserva() {
    }

	
    public TbReserva(TbLazer tbLazer, TbPessoa tbPessoa, Date dtaReserva, boolean flagConfirma) {
        this.tbLazer = tbLazer;
        this.tbPessoa = tbPessoa;
        this.dtaReserva = dtaReserva;
        this.flagConfirma = flagConfirma;
    }
    public TbReserva(TbLazer tbLazer, TbPessoa tbPessoa, Date dtaReserva, Date dtiInicioReserva, Date dtiFimReserva, boolean flagConfirma, Date dtaCadastroReserva) {
       this.tbLazer = tbLazer;
       this.tbPessoa = tbPessoa;
       this.dtaReserva = dtaReserva;
       this.dtiInicioReserva = dtiInicioReserva;
       this.dtiFimReserva = dtiFimReserva;
       this.flagConfirma = flagConfirma;
       this.dtaCadastroReserva = dtaCadastroReserva;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_reserva", unique=true, nullable=false)
    public Integer getIdtReserva() {
        return this.idtReserva;
    }
    
    public void setIdtReserva(Integer idtReserva) {
        this.idtReserva = idtReserva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_cod_lazer", nullable=false)
    public TbLazer getTbLazer() {
        return this.tbLazer;
    }
    
    public void setTbLazer(TbLazer tbLazer) {
        this.tbLazer = tbLazer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tb_cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_reserva", nullable=false, length=10)
    public Date getDtaReserva() {
        return this.dtaReserva;
    }
    
    public void setDtaReserva(Date dtaReserva) {
        this.dtaReserva = dtaReserva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dti_inicio_reserva", length=19)
    public Date getDtiInicioReserva() {
        return this.dtiInicioReserva;
    }
    
    public void setDtiInicioReserva(Date dtiInicioReserva) {
        this.dtiInicioReserva = dtiInicioReserva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dti_fim_reserva", length=19)
    public Date getDtiFimReserva() {
        return this.dtiFimReserva;
    }
    
    public void setDtiFimReserva(Date dtiFimReserva) {
        this.dtiFimReserva = dtiFimReserva;
    }

    
    @Column(name="flag_confirma", nullable=false)
    public boolean isFlagConfirma() {
        return this.flagConfirma;
    }
    
    public void setFlagConfirma(boolean flagConfirma) {
        this.flagConfirma = flagConfirma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_cadastro_reserva", length=10)
    public Date getDtaCadastroReserva() {
        return this.dtaCadastroReserva;
    }
    
    public void setDtaCadastroReserva(Date dtaCadastroReserva) {
        this.dtaCadastroReserva = dtaCadastroReserva;
    }




}


