package pojo;
// Generated 19/04/2018 19:35:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbReserva generated by hbm2java
 */
@Entity
@Table(name="tb_reserva"
    ,catalog="db_gecon"
)
public class TbReserva  implements java.io.Serializable {


     private Integer idtReserva;
     private TbLazer tbLazer;
     private TbPessoa tbPessoa;
     private Date dtaCadastroReserva;
     private Date dtaReserva;
     private Date dtaInicioReserva;
     private Date dtaFimReserva;
     private boolean flagConfirmaReserva;

    public TbReserva() {
    }

    public TbReserva(TbLazer tbLazer, TbPessoa tbPessoa, Date dtaCadastroReserva, Date dtaReserva, Date dtaInicioReserva, Date dtaFimReserva, boolean flagConfirmaReserva) {
       this.tbLazer = tbLazer;
       this.tbPessoa = tbPessoa;
       this.dtaCadastroReserva = dtaCadastroReserva;
       this.dtaReserva = dtaReserva;
       this.dtaInicioReserva = dtaInicioReserva;
       this.dtaFimReserva = dtaFimReserva;
       this.flagConfirmaReserva = flagConfirmaReserva;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_reserva", unique=true, nullable=false)
    public Integer getIdtReserva() {
        return this.idtReserva;
    }
    
    public void setIdtReserva(Integer idtReserva) {
        this.idtReserva = idtReserva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_lazer", nullable=false)
    public TbLazer getTbLazer() {
        return this.tbLazer;
    }
    
    public void setTbLazer(TbLazer tbLazer) {
        this.tbLazer = tbLazer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_cadastro_reserva", nullable=false, length=10)
    public Date getDtaCadastroReserva() {
        return this.dtaCadastroReserva;
    }
    
    public void setDtaCadastroReserva(Date dtaCadastroReserva) {
        this.dtaCadastroReserva = dtaCadastroReserva;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_reserva", nullable=false, length=10)
    public Date getDtaReserva() {
        return this.dtaReserva;
    }
    
    public void setDtaReserva(Date dtaReserva) {
        this.dtaReserva = dtaReserva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_inicio_reserva", nullable=false, length=19)
    public Date getDtaInicioReserva() {
        return this.dtaInicioReserva;
    }
    
    public void setDtaInicioReserva(Date dtaInicioReserva) {
        this.dtaInicioReserva = dtaInicioReserva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_fim_reserva", nullable=false, length=19)
    public Date getDtaFimReserva() {
        return this.dtaFimReserva;
    }
    
    public void setDtaFimReserva(Date dtaFimReserva) {
        this.dtaFimReserva = dtaFimReserva;
    }

    
    @Column(name="flag_confirma_reserva", nullable=false)
    public boolean isFlagConfirmaReserva() {
        return this.flagConfirmaReserva;
    }
    
    public void setFlagConfirmaReserva(boolean flagConfirmaReserva) {
        this.flagConfirmaReserva = flagConfirmaReserva;
    }




}


