package pojo;
// Generated 26/04/2018 19:07:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUsuario generated by hbm2java
 */
@Entity
@Table(name="tb_usuario"
    ,catalog="db_gecon"
)
public class TbUsuario  implements java.io.Serializable {


     private int idtUsuario;
     private TaMorador taMorador;
     private TdPerfil tdPerfil;
     private String nmeUsuario;
     private String pwdUsuario;

    public TbUsuario() {
    }

    public TbUsuario(int idtUsuario, TaMorador taMorador, TdPerfil tdPerfil, String nmeUsuario, String pwdUsuario) {
       this.idtUsuario = idtUsuario;
       this.taMorador = taMorador;
       this.tdPerfil = tdPerfil;
       this.nmeUsuario = nmeUsuario;
       this.pwdUsuario = pwdUsuario;
    }
   
     @Id 

    
    @Column(name="idt_usuario", unique=true, nullable=false)
    public int getIdtUsuario() {
        return this.idtUsuario;
    }
    
    public void setIdtUsuario(int idtUsuario) {
        this.idtUsuario = idtUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_morador", nullable=false)
    public TaMorador getTaMorador() {
        return this.taMorador;
    }
    
    public void setTaMorador(TaMorador taMorador) {
        this.taMorador = taMorador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_perfil", nullable=false)
    public TdPerfil getTdPerfil() {
        return this.tdPerfil;
    }
    
    public void setTdPerfil(TdPerfil tdPerfil) {
        this.tdPerfil = tdPerfil;
    }

    
    @Column(name="nme_usuario", nullable=false, length=80)
    public String getNmeUsuario() {
        return this.nmeUsuario;
    }
    
    public void setNmeUsuario(String nmeUsuario) {
        this.nmeUsuario = nmeUsuario;
    }

    
    @Column(name="pwd_usuario", nullable=false)
    public String getPwdUsuario() {
        return this.pwdUsuario;
    }
    
    public void setPwdUsuario(String pwdUsuario) {
        this.pwdUsuario = pwdUsuario;
    }




}


