package pojo;
// Generated 26/04/2018 19:07:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbVisita generated by hbm2java
 */
@Entity
@Table(name="tb_visita"
    ,catalog="db_gecon"
)
public class TbVisita  implements java.io.Serializable {


     private Integer idtOcorrencia;
     private TbPessoa tbPessoa;
     private TbResidencia tbResidencia;
     private Date dtaInicioVisita;
     private Date dtaFinalVisita;

    public TbVisita() {
    }

	
    public TbVisita(TbPessoa tbPessoa, TbResidencia tbResidencia, Date dtaInicioVisita) {
        this.tbPessoa = tbPessoa;
        this.tbResidencia = tbResidencia;
        this.dtaInicioVisita = dtaInicioVisita;
    }
    public TbVisita(TbPessoa tbPessoa, TbResidencia tbResidencia, Date dtaInicioVisita, Date dtaFinalVisita) {
       this.tbPessoa = tbPessoa;
       this.tbResidencia = tbResidencia;
       this.dtaInicioVisita = dtaInicioVisita;
       this.dtaFinalVisita = dtaFinalVisita;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_ocorrencia", unique=true, nullable=false)
    public Integer getIdtOcorrencia() {
        return this.idtOcorrencia;
    }
    
    public void setIdtOcorrencia(Integer idtOcorrencia) {
        this.idtOcorrencia = idtOcorrencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_pessoa", nullable=false)
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_residencia", nullable=false)
    public TbResidencia getTbResidencia() {
        return this.tbResidencia;
    }
    
    public void setTbResidencia(TbResidencia tbResidencia) {
        this.tbResidencia = tbResidencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_inicio_visita", nullable=false, length=10)
    public Date getDtaInicioVisita() {
        return this.dtaInicioVisita;
    }
    
    public void setDtaInicioVisita(Date dtaInicioVisita) {
        this.dtaInicioVisita = dtaInicioVisita;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_final_visita", length=10)
    public Date getDtaFinalVisita() {
        return this.dtaFinalVisita;
    }
    
    public void setDtaFinalVisita(Date dtaFinalVisita) {
        this.dtaFinalVisita = dtaFinalVisita;
    }




}


