package pojo;
// Generated 12/04/2018 19:01:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TdPerfil generated by hbm2java
 */
@Entity
@Table(name="td_perfil"
    ,catalog="db_gecon"
)
public class TdPerfil  implements java.io.Serializable {


     private Integer idtPerfil;
     private String dscPerfil;
     private Set<TbPessoa> tbPessoas = new HashSet<TbPessoa>(0);

    public TdPerfil() {
    }

	
    public TdPerfil(String dscPerfil) {
        this.dscPerfil = dscPerfil;
    }
    public TdPerfil(String dscPerfil, Set<TbPessoa> tbPessoas) {
       this.dscPerfil = dscPerfil;
       this.tbPessoas = tbPessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_perfil", unique=true, nullable=false)
    public Integer getIdtPerfil() {
        return this.idtPerfil;
    }
    
    public void setIdtPerfil(Integer idtPerfil) {
        this.idtPerfil = idtPerfil;
    }

    
    @Column(name="dsc_perfil", nullable=false, length=45)
    public String getDscPerfil() {
        return this.dscPerfil;
    }
    
    public void setDscPerfil(String dscPerfil) {
        this.dscPerfil = dscPerfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdPerfil")
    public Set<TbPessoa> getTbPessoas() {
        return this.tbPessoas;
    }
    
    public void setTbPessoas(Set<TbPessoa> tbPessoas) {
        this.tbPessoas = tbPessoas;
    }




}


